String.toLocaleString({

	"it": {
    "%game-intro"           : "Join the <strong>A-Tower Boys!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/simatowah\">git.io/simatowah</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Simmons images by <a href=\"http://simmons-hall.mit.edu/\" title=\"Simmons Hall | A-Tower | About\">Simmons Hall</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-A-tower #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'Fausto Uribe Tucker',
    '%4'                    : 'Diego Raygoza',
    '%8'                    : 'Oscar Hernandez',
    '%16'                   : 'Sergio Perez',
    '%32'                   : 'Quentin Thernize',
    '%64'                   : 'Peter Amenewolde',
    '%128'                  : 'Danny the manny',
    '%256'                  : 'Kevin Jamesss',
    '%512'                  : 'Null',
    '%1024'                 : 'Null',
    '%2048'                 : 'Kelsey',
    '%4096'                 : 'Null',
    '%8192'                 : 'Null',
    '%p0'                   : 'Fausto Uribe Tucker',
    '%p4'                   : 'Diego Raygoza',
    '%p8'                   : 'Oscar Hernandez',
    '%p16'                  : 'Sergio Perez',
    '%p32'                  : 'Quentin Therniza',
    '%p64'                  : 'Peter Amenewolde',
    '%p128'                 : 'Danny the Manny',
    '%p256'                 : 'Kevin Jamesssss',
    '%p512'                 : 'Null',
    '%p1024'                : 'Null',
    '%p2048'                : 'Kelsey',
    '%p4096'                : 'Null',
    '%p8192'                : 'Null'

	},

  "en": {
    "%game-intro"           : "Join the <strong>A-Tower Boys!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/simatowah\">git.io/simatowah</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Simmons images by <a href=\"http://simmons-hall.mit.edu/\" title=\"Simmons Hall | A-Tower | About\">Simmons Hall</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-A-Tower #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'Fausto Uribe Tucker',
    '%4'                    : 'Diego Raygoza',
    '%8'                    : 'Oscar Hernandez',
    '%16'                   : 'Sergio Perez',
    '%32'                   : 'Quentin Thernize',
    '%64'                   : 'Peter Amenewolde',
    '%128'                  : 'Danny the Manny',
    '%256'                  : 'Kevin Jamesss',
    '%512'                  : 'Null',
    '%1024'                 : 'Null',
    '%2048'                 : 'Kelsey',
    '%4096'                 : 'Null',
    '%8192'                 : 'Null',
    '%p0'                   : 'Fausto Uribe Tucker',
    '%p4'                   : 'Diego Raygoza',
    '%p8'                   : 'Oscar Hernandez',
    '%p16'                  : 'Sergio Perez',
    '%p32'                  : 'Quentin Therniza',
    '%p64'                  : 'Peter Amenewolde',
    '%p128'                 : 'Danny the Manny',
    '%p256'                 : 'Kevin Jamesssss',
    '%p512'                 : 'Null',
    '%p1024'                : 'Null',
    '%p2048'                : 'Kelsey',
    '%p4096'                : 'Null',
    '%p8192'                : 'Null'
  }

});
